name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/shared

      - name: Run Build
        run: npm run build
